/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Repository
         * @description Create Repository
         */
        post: operations["RepositoriesController_createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get repositories for username
         * @description Get repositories for username
         */
        get: operations["RepositoriesController_getRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get repository details
         * @description Get a single repository by owner username and slug
         */
        get: operations["RepositoriesController_getRepository"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fork repository
         * @description Copy a repository under the requester. One fork per repository per owner.
         */
        post: operations["RepositoriesController_forkRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}/star": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Star repository
         * @description Star a repository. Starring twice leaves the count unchanged.
         */
        post: operations["RepositoriesController_starRepository"];
        /**
         * Unstar repository
         * @description Remove the requester's star from a repository.
         */
        delete: operations["RepositoriesController_unstarRepository"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repository contents
         * @description One level of a directory at the requested ref - a branch or a commit sha - or the default branch when none is given, with the newest commit touching each entry. Directories report the newest commit anywhere beneath them.
         */
        get: operations["RepositoriesController_getRepositoryContents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}/blob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a file
         * @description Contents of a single file at the requested ref - a branch or a commit sha - or the default branch when none is given. Binary files come back base64-encoded, and a file past the inline size limit comes back without contents.
         */
        get: operations["RepositoriesController_getRepositoryBlob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a file
         * @description The raw bytes of a file. Images, audio, video and PDFs are served inline for the browser to render; everything else downloads.
         */
        get: operations["RepositoriesController_getRawBlob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List commits
         * @description History of a branch or commit, newest first, optionally narrowed to one path. Pages are cursor-based: pass a response `nextCursor` back as `cursor`.
         */
        get: operations["RepositoriesController_getRepositoryCommits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}/commits/{sha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a commit
         * @description One commit with the paths it changed, against its first parent. Accepts a full sha or any unambiguous prefix.
         */
        get: operations["RepositoriesController_getRepositoryCommit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}/commits/{sha}/patch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a commit as a patch
         * @description The commit as a git patch file, unparsed.
         */
        get: operations["RepositoriesController_getCommitPatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{slug}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repository branches
         * @description Every branch of the repository, and which one it opens on.
         */
        get: operations["RepositoriesController_getRepositoryBranches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pull requests */
        get: operations["PullRequestsController_getPullRequests"];
        put?: never;
        /** Open a pull request */
        post: operations["PullRequestsController_createPullRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls/compare/patch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The patch two branches would open a request with */
        get: operations["PullRequestsController_comparePatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The files two branches would open a request with */
        get: operations["PullRequestsController_compare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a pull request */
        get: operations["PullRequestsController_getPullRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a pull request title or description */
        patch: operations["PullRequestsController_updatePullRequest"];
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls/{number}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Commits a pull request adds */
        get: operations["PullRequestsController_getCommits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls/{number}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paths a pull request changes */
        get: operations["PullRequestsController_getFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls/{number}/patch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The patch itself, as text */
        get: operations["PullRequestsController_getPatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls/{number}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comments on a pull request */
        get: operations["PullRequestsController_getComments"];
        put?: never;
        /** Comment on a pull request */
        post: operations["PullRequestsController_createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls/{number}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge a pull request into its base branch */
        post: operations["PullRequestsController_mergePullRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/pulls/{number}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Close a pull request without merging */
        patch: operations["PullRequestsController_closePullRequest"];
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List issues */
        get: operations["IssuesController_getIssues"];
        put?: never;
        /** Open an issue */
        post: operations["IssuesController_createIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/issues/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an issue */
        get: operations["IssuesController_getIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit an issue title or description */
        patch: operations["IssuesController_updateIssue"];
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/issues/{number}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close an issue */
        post: operations["IssuesController_closeIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/issues/{number}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen a closed issue */
        post: operations["IssuesController_reopenIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/issues/{number}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comments on an issue */
        get: operations["IssuesController_getComments"];
        put?: never;
        /** Comment on an issue */
        post: operations["IssuesController_createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/issues/{number}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an issue comment */
        delete: operations["IssuesController_deleteComment"];
        options?: never;
        head?: never;
        /** Edit an issue comment */
        patch: operations["IssuesController_updateComment"];
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/issues/{number}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comments and events interleaved oldest-first */
        get: operations["IssuesController_getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/issues/{number}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the labels on an issue */
        put: operations["IssuesController_setIssueLabels"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/issues/{number}/assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the assignees on an issue */
        put: operations["IssuesController_setIssueAssignees"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List labels in a repository */
        get: operations["LabelsController_listLabels"];
        put?: never;
        /** Create a label */
        post: operations["LabelsController_createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{username}/{repo}/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a label */
        delete: operations["LabelsController_deleteLabel"];
        options?: never;
        head?: never;
        /** Update a label */
        patch: operations["LabelsController_updateLabel"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRepositoryRequestDTO: {
            name: string;
            description?: string;
        };
        CreateRepositoryResponseDTO: {
            id: string;
            slug: string;
        };
        ErrorResponseDTO: {
            message: string;
        };
        /** @enum {string} */
        RepositoryVisibility: "public" | "private";
        RepositoryParentEntity: {
            username: string;
            slug: string;
            name: string;
        };
        RepositoryEntity: {
            id: string;
            name: string;
            description?: string;
            slug: string;
            visibility: components["schemas"]["RepositoryVisibility"];
            lastPushedAt: string;
            createdAt: string;
            updatedAt: string;
            starCount: number;
            viewerHasStarred: boolean;
            forkCount: number;
            /** @description Slug of the viewer's own fork of this repository, if any */
            viewerForkSlug?: string | null;
            /** @description The repository this one was forked from */
            parent?: components["schemas"]["RepositoryParentEntity"] | null;
        };
        GetRepositoriesResponseDTO: {
            repositories: components["schemas"]["RepositoryEntity"][];
            /** @description Pass back as `cursor` for the next page. `null` on the last page. */
            nextCursor: string | null;
            hasMore: boolean;
        };
        ForkRepositoryRequestDTO: {
            name: string;
            description?: string;
            visibility: components["schemas"]["RepositoryVisibility"];
        };
        ForkRepositoryResponseDTO: {
            id: string;
            slug: string;
            username: string;
        };
        StarRepositoryResponseDTO: {
            starCount: number;
            viewerHasStarred: boolean;
        };
        CommitSummaryDTO: {
            /** @description Full 40-character commit sha. */
            sha: string;
            /** @description Commit subject - the first line of the message. */
            message: string;
            /** @description Committer timestamp, ISO 8601. */
            committedAt: string;
        };
        /**
         * @description `tree` is a directory, `commit` a submodule.
         * @enum {string}
         */
        TreeEntryType: "blob" | "tree" | "commit";
        TreeEntryDTO: {
            /** @description Entry name within the listed directory. */
            name: string;
            /** @description Full path from the repository root. */
            path: string;
            /** @description `tree` is a directory, `commit` a submodule. */
            type: components["schemas"]["TreeEntryType"];
            /**
             * @description Git file mode, e.g. `100644`.
             * @example 100644
             */
            mode: string;
            /** @description Object id of the blob or tree. */
            oid: string;
            /** @description Blob size in bytes; `null` for trees and submodules. */
            size: number | null;
            /** @description Newest commit touching this entry, or anything beneath it for a tree. `null` only if the index has not caught up with the ref. */
            lastCommit: components["schemas"]["CommitSummaryDTO"] | null;
        };
        GetRepositoryContentsResponseDTO: {
            /**
             * @description Ref that was listed, always fully qualified.
             * @example refs/heads/main
             */
            ref: string;
            /**
             * @description Normalized directory that was listed, with a trailing slash. Empty at the root.
             * @example src/services/
             */
            path: string;
            /**
             * @description Commits reachable from the ref. `0` for an unborn ref.
             * @example 128
             */
            commitCount: number;
            /** @description Tip commit of the ref. `null` when nothing has been pushed yet. */
            commit: components["schemas"]["CommitSummaryDTO"] | null;
            /** @description One level of the directory: directories first (submodules among them), then files, each group alphabetical. Case is a minor difference, so `readme.md` and `README.md` sit together rather than in separate blocks, and embedded numbers order naturally (`file2` before `file10`). Empty for an unborn ref or a path that is not a directory. */
            entries: components["schemas"]["TreeEntryDTO"][];
        };
        /**
         * @description `base64` for binary files, and for anything that is not valid UTF-8.
         * @enum {string}
         */
        BlobEncoding: "utf-8" | "base64";
        GetRepositoryBlobResponseDTO: {
            /**
             * @description Ref that was read, always fully qualified.
             * @example refs/heads/main
             */
            ref: string;
            /**
             * @description Normalized path of the file.
             * @example src/main.ts
             */
            path: string;
            /** @description Object id of the blob. */
            oid: string;
            /** @description File size in bytes. */
            size: number;
            /** @description `base64` for binary files, and for anything that is not valid UTF-8. */
            encoding: components["schemas"]["BlobEncoding"];
            /** @description File contents, `null` when the file is past the inline size limit. */
            content: string | null;
            /** @description Newest commit touching this file. */
            commit: components["schemas"]["CommitSummaryDTO"] | null;
        };
        CommitDTO: {
            /** @description Full 40-character commit sha. */
            sha: string;
            /** @description Commit subject, the first line of the message. */
            subject: string;
            /** @description The rest of the message. Empty when there is none. */
            body: string;
            authorName: string;
            authorEmail: string;
            /** @description Committer timestamp, ISO 8601. */
            committedAt: string;
        };
        GetRepositoryCommitsResponseDTO: {
            /**
             * @description Ref that was walked, always fully qualified.
             * @example refs/heads/main
             */
            ref: string;
            /**
             * @description Position of this page's first commit in the walk, 1-based. `0` when the page is empty.
             * @example 41
             */
            from: number;
            /**
             * @description Position of this page's last commit. `0` when the page is empty.
             * @example 60
             */
            to: number;
            /**
             * @description Commits the walk can reach in total, narrowed by `path` when one is given.
             * @example 128
             */
            total: number;
            /** @description Newest first. */
            commits: components["schemas"]["CommitDTO"][];
            /** @description Pass back as `cursor` for the next page. `null` on the last page. */
            nextCursor: string | null;
        };
        CommitFileDTO: {
            /** @description `A` added, `M` modified, `D` deleted. */
            status: string;
            path: string;
        };
        GetRepositoryCommitResponseDTO: {
            /** @description Full 40-character commit sha. */
            sha: string;
            /** @description Commit subject, the first line of the message. */
            subject: string;
            /** @description The rest of the message. Empty when there is none. */
            body: string;
            authorName: string;
            authorEmail: string;
            /** @description Committer timestamp, ISO 8601. */
            committedAt: string;
            /** @description Paths this commit changed, against its first parent. */
            files: components["schemas"]["CommitFileDTO"][];
        };
        GetRepositoryBranchesResponseDTO: {
            /**
             * @description Branch the repository opens on. `null` when nothing has been pushed yet.
             * @example main
             */
            defaultBranch: string | null;
            /**
             * @description Branch names, without the `refs/heads/` prefix, ordered by name.
             * @example [
             *       "main",
             *       "feat/contents"
             *     ]
             */
            branches: string[];
        };
        CreatePullRequestRequestDTO: {
            /** @example Add a rate limiter */
            title: string;
            body?: string;
            /**
             * @description Branch to merge into, in this repository.
             * @example main
             */
            base: string;
            /**
             * @description Branch to merge from. `owner:branch` for a fork, or a bare branch name for this repository.
             * @example alice:feature
             */
            head: string;
        };
        /** @enum {string} */
        PullRequestState: "open" | "closed" | "merged";
        PullRequestSideDTO: {
            /** @example bob */
            username: string;
            /** @example ghost */
            slug: string;
            /** @example main */
            ref: string;
        };
        PullRequestDTO: {
            id: string;
            /** @description Per base repository, and what the URL carries. */
            number: number;
            title: string;
            body: string | null;
            state: components["schemas"]["PullRequestState"];
            base: components["schemas"]["PullRequestSideDTO"];
            head: components["schemas"]["PullRequestSideDTO"];
            /** @description Head tip as of the last read. */
            headSha: string;
            mergeCommitSha: string | null;
            authorUsername: string;
            createdAt: string;
            updatedAt: string;
        };
        /** @enum {string} */
        PullRequestStateFilter: "open" | "closed" | "merged" | "all";
        GetPullRequestsResponseDTO: {
            pullRequests: components["schemas"]["PullRequestDTO"][];
            /** @description Matching the state filter, ignoring the page. */
            total: number;
            nextCursor: string | null;
            hasMore: boolean;
        };
        PullRequestFileDTO: {
            /** @description `A` added, `M` modified, `D` deleted. */
            status: string;
            path: string;
            additions: number;
            deletions: number;
            /** @description Line counts are meaningless when true. */
            binary: boolean;
        };
        CompareResponseDTO: {
            /** @description Merge base of the two branches. */
            from: string;
            /** @description Head tip the diff is taken to. */
            to: string;
            files: components["schemas"]["PullRequestFileDTO"][];
        };
        PullRequestDetailDTO: {
            id: string;
            /** @description Per base repository, and what the URL carries. */
            number: number;
            title: string;
            body: string | null;
            state: components["schemas"]["PullRequestState"];
            base: components["schemas"]["PullRequestSideDTO"];
            head: components["schemas"]["PullRequestSideDTO"];
            /** @description Head tip as of the last read. */
            headSha: string;
            mergeCommitSha: string | null;
            authorUsername: string;
            createdAt: string;
            updatedAt: string;
            /** @description Commit the two branches diverged from. */
            mergeBase: string | null;
            /** @description Commits the head branch adds on top of the base. */
            commitCount: number;
            changedFiles: number;
            additions: number;
            deletions: number;
            /** @description Whether the merge is conflict-free right now. Never cached. */
            mergeable: boolean;
        };
        GetPullRequestCommitsResponseDTO: {
            /** @description Newest first. */
            commits: components["schemas"]["CommitDTO"][];
            total: number;
            nextCursor: string | null;
        };
        GetPullRequestFilesResponseDTO: {
            /** @description Commit the diff is taken from, the merge base of the two branches. */
            from: string;
            /** @description Head tip the diff is taken to. */
            to: string;
            files: components["schemas"]["PullRequestFileDTO"][];
        };
        PullRequestCommentDTO: {
            id: string;
            /** @description Markdown, rendered by the client. */
            body: string;
            authorUsername: string;
            createdAt: string;
            updatedAt: string;
        };
        GetPullRequestCommentsResponseDTO: {
            comments: components["schemas"]["PullRequestCommentDTO"][];
        };
        CreatePullRequestCommentRequestDTO: {
            body: string;
        };
        MergePullRequestRequestDTO: {
            /** @description Merge commit subject. Defaults to the request title. */
            title?: string;
        };
        MergePullRequestResponseDTO: {
            mergeCommitSha: string;
            /** @description Sequence the merge landed at in the base log. */
            seq: number;
        };
        UpdatePullRequestRequestDTO: {
            /** @example Add a rate limiter */
            title?: string;
            /** @description Markdown. `null` clears the description. */
            body?: string | null;
        };
        CreateIssueRequestDTO: {
            /** @example Login fails with 500 on Safari */
            title: string;
            /** @description Markdown. */
            body?: string;
            /**
             * @description Label names in this repository.
             * @example [
             *       "bug"
             *     ]
             */
            labels?: string[];
            /**
             * @description Usernames to assign.
             * @example [
             *       "octocat"
             *     ]
             */
            assignees?: string[];
        };
        /** @enum {string} */
        IssueState: "open" | "closed";
        LabelDTO: {
            id: string;
            /** @example bug */
            name: string;
            description: string | null;
            /**
             * @description 6 hex chars, no `#`. The client adds `#` when rendering.
             * @example d73a4a
             */
            color: string;
            createdAt: string;
            updatedAt: string;
        };
        IssueDTO: {
            id: string;
            /** @description Per repository, and what the URL carries. */
            number: number;
            title: string;
            body: string | null;
            state: components["schemas"]["IssueState"];
            authorUsername: string;
            closedByUsername: string | null;
            labels: components["schemas"]["LabelDTO"][];
            /**
             * @example [
             *       "octocat"
             *     ]
             */
            assignees: string[];
            commentCount: number;
            closedAt: string | null;
            createdAt: string;
            updatedAt: string;
            /** @description True when the requesting user is the author or can write to the repository. */
            viewerCanEdit: boolean;
        };
        /** @enum {string} */
        IssueStateFilter: "open" | "closed" | "all";
        GetIssuesResponseDTO: {
            issues: components["schemas"]["IssueDTO"][];
            /** @description Matching every filter except `state`. */
            total: number;
            openCount: number;
            closedCount: number;
            nextCursor: string | null;
            hasMore: boolean;
        };
        IssueDetailDTO: {
            id: string;
            /** @description Per repository, and what the URL carries. */
            number: number;
            title: string;
            body: string | null;
            state: components["schemas"]["IssueState"];
            authorUsername: string;
            closedByUsername: string | null;
            labels: components["schemas"]["LabelDTO"][];
            /**
             * @example [
             *       "octocat"
             *     ]
             */
            assignees: string[];
            commentCount: number;
            closedAt: string | null;
            createdAt: string;
            updatedAt: string;
            /** @description True when the requesting user is the author or can write to the repository. */
            viewerCanEdit: boolean;
        };
        UpdateIssueRequestDTO: {
            /** @example Login fails with 500 on Safari */
            title?: string;
            /** @description Markdown. `null` clears the description. */
            body?: string | null;
        };
        IssueCommentDTO: {
            id: string;
            /** @description Markdown, rendered by the client. */
            body: string;
            authorUsername: string;
            createdAt: string;
            updatedAt: string;
        };
        GetIssueCommentsResponseDTO: {
            comments: components["schemas"]["IssueCommentDTO"][];
        };
        CreateIssueCommentRequestDTO: {
            body: string;
        };
        UpdateIssueCommentRequestDTO: {
            body: string;
        };
        IssueTimelineCommentDTO: {
            /**
             * @example comment
             * @enum {string}
             */
            kind: "comment";
            id: string;
            body: string;
            authorUsername: string;
            createdAt: string;
            updatedAt: string;
        };
        /** @enum {string} */
        IssueEventType: "opened" | "closed" | "reopened" | "renamed" | "edited" | "labeled" | "unlabeled" | "assigned" | "unassigned";
        IssueTimelineEventDTO: {
            id: string;
            type: components["schemas"]["IssueEventType"];
            actorUsername: string;
            labelName: string | null;
            assigneeUsername: string | null;
            oldTitle: string | null;
            newTitle: string | null;
            createdAt: string;
        };
        IssueTimelineEventItemDTO: {
            /**
             * @example event
             * @enum {string}
             */
            kind: "event";
            event: components["schemas"]["IssueTimelineEventDTO"];
            createdAt: string;
        };
        GetIssueTimelineResponseDTO: {
            /** @description Comments and events interleaved oldest-first, exactly as rendered. */
            timeline: (components["schemas"]["IssueTimelineCommentDTO"] | components["schemas"]["IssueTimelineEventItemDTO"])[];
        };
        SetIssueLabelsRequestDTO: {
            /**
             * @description Full replacement set. Label names in this repository.
             * @example [
             *       "bug",
             *       "help wanted"
             *     ]
             */
            names: string[];
        };
        SetIssueAssigneesRequestDTO: {
            /**
             * @description Full replacement set. Usernames to assign.
             * @example [
             *       "octocat"
             *     ]
             */
            usernames: string[];
        };
        GetLabelsResponseDTO: {
            labels: components["schemas"]["LabelDTO"][];
        };
        CreateLabelRequestDTO: {
            /** @example bug */
            name: string;
            /** @example Something is not working */
            description?: string;
            /** @example d73a4a */
            color: string;
        };
        UpdateLabelRequestDTO: {
            /** @example bug */
            name?: string;
            /** @description `null` clears the description. */
            description?: string | null;
            /** @example d73a4a */
            color?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RepositoriesController_createRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequestDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRepositoryResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_getRepositories: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned as `nextCursor` by the previous page. Omit for the first page. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRepositoriesResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_getRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryEntity"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_forkRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForkRepositoryRequestDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForkRepositoryResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_starRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StarRepositoryResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_unstarRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StarRepositoryResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_getRepositoryContents: {
        parameters: {
            query?: {
                /** @description Directory to list, relative to the repository root. Omit for the root. Slashes may be sent percent-encoded (`src%2Fdeep`); they are decoded once, so an already-decoded `src/deep` works too. */
                path?: string;
                /** @description Branch or commit sha to list. Accepts `main`, `refs/heads/main` or a commit sha. Omit for the default branch. */
                ref?: string;
            };
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRepositoryContentsResponseDTO"];
                };
            };
            /** @description The `path` query parameter is not a repository-relative directory. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_getRepositoryBlob: {
        parameters: {
            query: {
                /** @description File to read, relative to the repository root. */
                path: string;
                /** @description Branch, tag-free ref or commit sha to read from. Accepts `main`, `refs/heads/main` or a commit sha. Omit for the default branch. */
                ref?: string;
            };
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRepositoryBlobResponseDTO"];
                };
            };
            /** @description The `path` query parameter is not a repository-relative file. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_getRawBlob: {
        parameters: {
            query: {
                /** @description File to read, relative to the repository root. */
                path: string;
                /** @description Branch, tag-free ref or commit sha to read from. Accepts `main`, `refs/heads/main` or a commit sha. Omit for the default branch. */
                ref?: string;
            };
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_getRepositoryCommits: {
        parameters: {
            query?: {
                /** @description Branch or commit sha to walk. Omit for the default branch. */
                ref?: string;
                /** @description Only commits touching this path. */
                path?: string;
                /** @description Sha to resume from, taken from a previous `nextCursor`. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRepositoryCommitsResponseDTO"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_getRepositoryCommit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                slug: string;
                sha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRepositoryCommitResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_getCommitPatch: {
        parameters: {
            query?: {
                /** @description Limit the patch to one path. */
                path?: string;
            };
            header?: never;
            path: {
                username: string;
                slug: string;
                sha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example  */
                    "text/x-patch": unknown;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    RepositoriesController_getRepositoryBranches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRepositoryBranchesResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_getPullRequests: {
        parameters: {
            query?: {
                state?: components["schemas"]["PullRequestStateFilter"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                username: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPullRequestsResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_createPullRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePullRequestRequestDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_comparePatch: {
        parameters: {
            query: {
                /** @description Branch the changes would merge into. */
                base: string;
                /** @description Branch the changes come from, `owner:branch` for a fork. */
                head: string;
                /** @description Limit the patch to one path. */
                path?: string;
            };
            header?: never;
            path: {
                username: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_compare: {
        parameters: {
            query: {
                /** @description Branch the changes would merge into. */
                base: string;
                /** @description Branch the changes come from, `owner:branch` for a fork. */
                head: string;
            };
            header?: never;
            path: {
                username: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_getPullRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestDetailDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_updatePullRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePullRequestRequestDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_getCommits: {
        parameters: {
            query?: {
                /** @description Sha to resume from, taken from a previous `nextCursor`. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPullRequestCommitsResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_getFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPullRequestFilesResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_getPatch: {
        parameters: {
            query?: {
                /** @description Limit the patch to one path. */
                path?: string;
            };
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_getComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPullRequestCommentsResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePullRequestCommentRequestDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestCommentDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_mergePullRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergePullRequestRequestDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergePullRequestResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    PullRequestsController_closePullRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_getIssues: {
        parameters: {
            query?: {
                state?: components["schemas"]["IssueStateFilter"];
                /** @description Full-text search over title and body. */
                q?: string;
                /** @description Filter by author username. */
                author?: string;
                /** @description Filter by assignee username. */
                assignee?: string;
                /** @description Comma-separated label names. An issue must carry all of them. */
                labels?: string;
                sort?: "created" | "updated" | "comments";
                direction?: "asc" | "desc";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                username: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetIssuesResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_createIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIssueRequestDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_getIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetailDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_updateIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssueRequestDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_closeIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_reopenIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_getComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetIssueCommentsResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIssueCommentRequestDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueCommentDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssueCommentRequestDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueCommentDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_getTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetIssueTimelineResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_setIssueLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetIssueLabelsRequestDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    IssuesController_setIssueAssignees: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetIssueAssigneesRequestDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    LabelsController_listLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetLabelsResponseDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    LabelsController_createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLabelRequestDTO"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    LabelsController_deleteLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    LabelsController_updateLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                repo: string;
                labelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLabelRequestDTO"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelDTO"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
}
